### ISSUE TITLE
Add message to PWA To Do List for when all surveys are completed

### ISSUE THREAD

**Issue by robertsamm** [episphere/connect#1227]
We would like to add a message that appears on the to do list section when a participant has all surveys/activities moved to the 'completed' tab and doesn't have any surveys to complete. As right now when they don't have any activities the to do list is blank and the way it displays almost looks like the to do list hasn't properly loaded.

@depietrodeanna please propose final language to use and add to list to get Spanish translated. Perhaps something like 'You currently do not have any new surveys to complete. We will notify you when a new survey or study activity becomes available. Thank you for your contributions to Connect!'

![Image](https://github.com/user-attachments/assets/0f91102b-4d8e-4493-92dc-ad71042fb09e)

**Comment by depietrodeanna** [comment]
Message in English: "You've finished all available Connect surveys. We will reach out when there are new surveys and study activities for you to complete. Thank you for your contributions to this study!"

Will get translated to Spanish.

**Comment by depietrodeanna** [comment]
Spanish translation of this message:
"Ha completado todas las encuestas de Connect disponibles. Nos comunicaremos con usted cuando haya nuevas encuestas y actividades de estudio para completar. ¡Gracias por sus contribuciones al estudio!"

**Comment by robertsamm** [comment]
@depietrodeanna to test from Ops/Comms end - Deanna let us know if this doesn't fit into your priorities

**Comment by sonyekere** [comment]
Brian to look into this today.

**Comment by bransteitterbr** [comment]
Merged and ready for dev testing

**Comment by robertsamm** [comment]
@depietrodeanna are you able to test this one or do you need assistance?

**Comment by depietrodeanna** [comment]
I can test this! I need to pull a Connect ID who has completed all of their surveys or just go through the surveys available for a test account, I'm not really sure the best way to grab the former so I'll prob just use a fresh account that has just the baseline survey and complete it.

**Comment by bransteitterbr** [comment]
@depietrodeanna This is ready for retesting

**Comment by depietrodeanna** [comment]
This looks good! @bransteitterbr I'm curious how technically simple it would be to remove the second yellow bar message that appears about taking a survey in another language in these situations- when someone has no surveys to complete and we display the "you have no available surveys" message, could we remove the other "to take a survey in a different language" message? It would only be for those scenarios. If this is technically challenging, we are OK to leave as is.

**Comment by bransteitterbr** [comment]
@depietrodeanna It wasn't a big change.  I have merged the pr.  Feel free to test it when you have time.

**Comment by depietrodeanna** [comment]
Great! This looks good- checked that the only message to appear for someone who has completed all surveys is the new message we are implementing this release. And for someone who has yet to complete all surveys, the other yellow bar message about completing the survey in a different language is still showing up as expected. Ready for Stage @bransteitterbr  @sonyekere
