### ISSUE TITLE
Address Sign In Discrepancies found in QC Report

### ISSUE THREAD

**Issue by sonyekere** [episphere/connect#986]
**- Placeholder for requirements,** Madhuri shared the below following:

"In QC report, it was found that for a participant that had signed in but was missing sign in time, they were actually verified. I double checked that their sign-in flag = “yes” but sign-in time is null so I’m unsure why this is happening.

I did a quick check of the individuals that have signed in but are missing sign in time (n = 81) and it’s a mix of verification status = verified, not yet verified, and duplicate"

**Comment by mnataraj92** [comment]
@bransteitterbr The fix you implemented was for participants with a duplicate status that have signed in but were missing sign in time. When looking at the data, there are a handful of participants with a verification status of 'verified' or 'not yet verified' that have signed in but are also missing sign-in time. 

Would you be able to look into a fix for participants with these verification statuses as well?

**Comment by sonyekere** [comment]
This issue will be revisited in the June or July release.

**Comment by sonyekere** [comment]
Hi All! We deprioritized this issue in May due to other items taking priority. Is this discrepancy an existing concern that should be addressed in the July or August release ?

**Comment by JoeArmani** [comment]
Hi @mnataraj92, I was just assigned this issue. When you have time, will you answer a few questions for me?

• What's the concept ID for this sign-in timestamp?
• Should it be set on the first login only, or us it updated every login?
• Do we want to set this on the next login for participants where this timestamp is missing?
• Can I see some examples where it wasn't set? If there's a Box doc or report I can look at, that would be great.

Thanks!

**Comment by mnataraj92** [comment]
• What's the concept ID for this sign-in timestamp?
The sign in flag is d_230663853 and the sign in timestamp is d_335767902. If the sign in flag = yes then the timestamp should be populated. 

• Should it be set on the first login only, or us it updated every login?
Sign-in timestamp should be set on the first login only. It should not update. 

• Do we want to set this on the next login for participants where this timestamp is missing?
@FrogGirl1123 @brotzmanmj I'm not sure when we'd want this timestamp set to for participants where it's missing. The sign-in timestamp should be prior to the consent timestamp so should this be set to a timestamp prior to the consent timestamp? Or should it be set to the next login time? 

• Can I see some examples where it wasn't set? If there's a Box doc or report I can look at, that would be great.
https://nih.app.box.com/file/1688105056791

• Is there any other important background information you think I should have on this issue?
Not that I'm aware of aside from what's already in the issue. I think a fix had been pushed for this a while ago but it didn't capture everyone that had a missing sign in timestamp where it shouldn't have been missing.

**Comment by brotzmanmj** [comment]
For this:
• Do we want to set this on the next login for participants where this timestamp is missing?
@FrogGirl1123 @brotzmanmj I'm not sure when we'd want this timestamp set to for participants where it's missing. The sign-in timestamp should be prior to the consent timestamp so should this be set to a timestamp prior to the consent timestamp? Or should it be set to the next login time?

It depends what impact this is having on the analytics. From my perspective, if it is missing and we cannot grab the real value from wherever it is that sign in data come from in google, I think we should leave it as missing since this raw data. We can interpolate to something on an analysis-by-analysis basis depending on what meets the needs of the particular analysis. @FrogGirl1123  do you agree?

For the background information: We found out several months into the study launch that variable was not being captured and stored. We figured out why and then we started storing it. So for a time at the beginning of the study, it will be missing. The problem then became, even after we fixed it and started storing it, there are still occasions where it does not get stored and we don't know why.

**Comment by JoeArmani** [comment]
Thanks, @mnataraj92, for these responses and @brotzmanmj, for the context and background information.

**Comment by FrogGirl1123** [comment]
@brotzmanmj and @mnataraj92 I think we should leave it missing for those who don't have it and make decisions on what to populate it with, if anything, on an analytic case by case.  For example, Jake needs a value there for some of the coding he's doing, so he just populates it with the next date available, if sign-in date is missing use consent date if consent date is missing use user profile date.

**Comment by brotzmanmj** [comment]
@FrogGirl1123  just to confirm, so you're suggesting for the raw data it will be left missing. And depending on the analytic need, it would be populated in a way that makes sense for the specific purpose? I would be in agreement with that. 

Are there some sign-in timestamps that are non-missing but clearly erroneous in the raw data? (like after consent?)

And are there some that are still not getting recorded in recent days/months or is it resolved in prod now prospectively so we are consistently getting them?

**Comment by mnataraj92** [comment]
There are some time stamps that are after consent but those stem from issues in the past where sign in time kept updating each time someone signed in and that has since been fixed. There are still current time stamps that are not being recorded for people that have recently signed in so this issue is still ongoing.

**Comment by JoeArmani** [comment]
@brotzmanmj @FrogGirl1123 

There are two primary aspects to this issue:
(1) Stop it from happening in the future.
(2) Look into repairing existing cases (if you’d like).

I’m making good progress on both, but I want your opinion on (2):

We have access to the participant’s Firestore Authentication profile metadata when they log in to MyConnect. That includes a `creationTime` property: a timestamp set at Firebase Auth account creation.

According to the docs, this timestamp is set on account creation and retained for the life of the Firebase auth account. This aligns perfectly with our firstSignInTime 335767902.

Docs:
https://firebase.google.com/docs/reference/js/auth.usermetadata
https://firebase.google.com/docs/reference/admin/node/firebase-admin.auth.usermetadata


We can use this Firebase Auth `creationTime` to repair missing instances of 335767902 when a participant signs into MyConnect.

- Run a check when we pull participant data on MyConnect login to determine whether 335767902 has been set.
-If yes, continue forward in MyConnect as usual.
-If no, run a repair process in the background:

Repair process:
- Get the account creation time from the Firebase Authentication profile.
- QC check: Compare that timestamp to the HIPAA authorization (262613359) timestamp. It should always come before the HIPAA timestamp.
- If that QC check passes, write the missing first sign-in timestamp to the participant profile. Then, on subsequent logins, the initial ‘if 335767902 exists’ check will pass.



Questions:

(1) Do you want this repair process implemented?
(2) If yes, do you want it to run for all participants, or do you want me to set a cutoff so this doesn’t run for older cases with missing first sign in timestamps?

We can use other other timestamps set early during the sign-up process to set a cutoff, such as these:
471593703 recruitment type flat ts
262613359: HIPAA authorization ts
454445267: creation of derived completion time variables
430551721: UP Submitted ts

**Comment by brotzmanmj** [comment]
Here are my thoughts...
(1) I would say yes, what you're describing makes sense to me to implement
(2) You're suggesting to run this upon login, so the next time a participant logs into the system, one person at a time, as opposed to running it for everyone in the cohort? And only for consented participants? I don't envision wanting a cutoff for older cases, but it does make sense that our priority would be to have it for consented participants (also in which case the HIPAA timestamp would be available). @FrogGirl1123 would do you think?

**Comment by FrogGirl1123** [comment]
@JoeArmani, I like the process you have outlined.  I agree with @brotzmanmj  that there is not reason to have a cutoff for older cases.  Is there a reason to wait for a login or could this process just be run in batches for all signed-in participants, prioritizing those that have consented?

**Comment by JoeArmani** [comment]
@brotzmanmj @FrogGirl1123 Thank you both for the feedback.

Moving forward, the first sign-in timestamp update is built directly into the MyConnect account setup flow instead of being a separate operation.

The repair operation is tested and implemented in a PR I just posted. Yes, this version will update one participant at a time as participants with the missing first sign-in timestamp log back in.

My reasoning for the consent timestamp sanity check is that we don’t typically access the Firebase Auth account for anything other than authentication status and uid, so the consent timestamp is just a guardrail to ensure we’re getting the correct value. I can remove it if we want to include participants that haven’t consented.

I can look into accessing that Firebase Auth data through the Firebase Admin package to see if we can get the  `creationTime` that way. If we can, it would be straightforward to query the impacted participants and run that repair directly on those profiles as a one-time operation.

**Comment by JoeArmani** [comment]
These PRs are in review.

Testing this update:
---
•Sign up with a valid PIN number
•Sign up with an invalid PIN number (this falls back to the passive recruit flow)
•Sign up without a PIN number

•Ensure the first sign-in timestamp (335767902) is written in all cases
•Ensure the PIN number (379080287) or 'I do not have a PIN' (828729648 ) values are written depending on the case.

•Delete the first sign-in timestamp for an existing participant and check that it's repaired (re-written) after logging in.

**Comment by JoeArmani** [comment]
This is in dev and ready to test

**Comment by JoeArmani** [comment]
@brotzmanmj @FrogGirl1123

We can access this `creationTime` property from the Firebase Auth account for a single-use function. I have an update ready to run alongside this next release that should repair the old missing timestamp cases.

It should work wherever the Firebase Auth account exists and will run on participants where the sign-in flag is present and the timestamp is missing, regardless of consented status. I'll use a predefined list of participant tokens from BQ matching these conditions.

A test run in dev gave the expected results.

**Dev screenshots**

**From BQ Dev:**
<img width="920" alt="Dev - FirstSignInTimestamp - before" src="https://github.com/user-attachments/assets/bff854db-27e8-476f-b1a8-388909e9c684" />

**Script output:**
<img width="824" alt="Screenshot 2025-01-22 at 12 08 35 PM" src="https://github.com/user-attachments/assets/e7b9fd12-172e-40bc-8972-4c2fa15f9408" />

**Comment by robertsamm** [comment]
@cunnaneaq or @JoeArmani do we have PINs already set up in dev that we can use to test this?

**Comment by cunnaneaq** [comment]
I don't have any accounts with PINs

**Comment by JoeArmani** [comment]
@robertsamm Okay, I can get a couple created.

**Comment by robertsamm** [comment]
Thanks @JoeArmani and if it's easier - I can also reach out to HP for PINs. Just let me know!

**Comment by JoeArmani** [comment]
Hi @robertsamm, here are two valid PIN numbers. Site code is 13 for both participants, and it should skip the healthcare provider selection page when a valid PIN match is entered found. Let me know if you need any other PINs for testing. Thanks.

<img width="452" alt="Image" src="https://github.com/user-attachments/assets/65dceb3d-cad5-4d25-a406-12c347be1838" />

**Comment by robertsamm** [comment]
Thanks @JoeArmani! I'll work on testing these scenarios!

**Comment by robertsamm** [comment]
Hi @JoeArmani - I tested the following scenarios. All seemed to work as expected. On the SMDB I can see that the 'D/T First Sign-In', 'PIN' and 'PIN Entered' all look correct based on the data entered. Do you want to check the backend data?

And for this scenario 'Delete the first sign-in timestamp for an existing participant and check that it's repaired (re-written) after logging in' - after you check the backend data do you want to delete the timestamp for the first test scenario and then I can try relogging back in?

Test participants:
•Sign up with a valid PIN number.
Login email: [SignInTesting2@mailinator.com](mailto:SignInTesting2@mailinator.com)
Valid PIN entered: W2GRCB
Sign in Time: 1/24/25 ~10:05am
Connect ID: 7691613290
Workflow: entered active workflow as expected, skipped healthcare provider qx

•Sign up with an invalid PIN number (this falls back to the passive recruit flow).
Login Email: [SignInTesting3@mailinator.com](mailto:SignInTesting3@mailinator.com)
Invalid PIN entered: 000000
Sign in Time: 1/24/25 ~10:12am
Connect ID: 3275851123
Workflow: entered passive workflow as expected, had to select healthcare provider

•Sign up without a PIN number.
Login Email: [SignInTesting4@mailinator.com](mailto:SignInTesting4@mailinator.com) 
PIN entered: ‘I do not have a PIN’
Sign in Time: 1/24/25 ~10/15am
Connect ID: 1588491134
Workflow: entered passive workflow as expected, had to select healthcare provider

**Comment by JoeArmani** [comment]
Perfect. Thanks @robertsamm.

Looks good in Firestore. Entered PINs were recorded under 379080287, and the 'I do not have a PIN' variable 828729648 was set for the third case. The valid PIN sign-up correctly attached the participant to the existing shell record.

I deleted the first sign-in timestamp, 335767902, for the first participant (Connect ID 7691613290).

It should repopulate here on your next sign-in with that participant.
<img width="800" alt="Image" src="https://github.com/user-attachments/assets/b2fe63e0-1686-4c9a-a5bd-7be4f4d9ce2b" />

**Comment by robertsamm** [comment]
Thanks @JoeArmani, I just resigned in with this participant at 11:34am. The timestamp in the SMDB is showing the time I first signed in at 10:03am. Just wanted to confirm that is expected?

**Comment by JoeArmani** [comment]
Excellent, thanks. Yes, we want that original sign-up timestamp where the Firebase Auth account was created on the first sign-in action. It should always be before the consent and other timestamps generated during the sign-up process.

Confirming it repopulated in Firestore. Thanks for testing!
<img width="794" alt="Image" src="https://github.com/user-attachments/assets/b8eb23a0-518f-438e-a0b7-839d0fdd46ab" />

**Comment by JoeArmani** [comment]
Ready for stage

**Comment by robertsamm** [comment]
Hi @JoeArmani I have tested this in stage. My testing scenarios are below. All looked good for the PINs and timestamps on the SMDB. Once you look at Firestore and delete the timestamp of the first account let me know and I'll resign in.

•Sign up with a valid PIN number.
Login email: [SignInTesting2@mailinator.com](mailto:SignInTesting2@mailinator.com)
Valid PIN entered: FCF4A3
Sign in Time: 1/28 at ~10:58am ET
Connect ID: 8018314410

•Sign up with an invalid PIN number (this falls back to the passive recruit flow).
Login Email: [SignInTesting5@mailinator.com](mailto:SignInTesting5@mailinator.com)
Invalid PIN entered: 000000
Sign in Time: 1/28 at ~11:06am ET
Connect ID: 2115607890

•Sign up without a PIN number.
Login Email: [SignInTesting3@mailinator.com](mailto:SignInTesting3@mailinator.com)
PIN entered: ‘I do not have a PIN’
Sign in Time: 1/28 at ~11:03am ET
Connect ID: 5890840475

**Comment by JoeArmani** [comment]
Thanks, @robertsamm. Everything looks good in Firestore. I deleted the first participant's 335767902 first sign-in timestamp, so that's ready for you to sign in again and test the repair process.

<img width="995" alt="Image" src="https://github.com/user-attachments/assets/072dd4b9-39a0-4f3a-81ff-e59dac4112af" />

**Comment by robertsamm** [comment]
Thanks @JoeArmani, I re-signed in the first participant around ~12:33pm ET. The SMDB shows the sign in timestamp as the original timestamp of 10:58am ET, as expected! If all looks good to you - then this is ready for prod.

**Comment by JoeArmani** [comment]
Perfect, yes, it repopulated as expected and looks good in Firestore. Thanks for testing!

<img width="597" alt="Image" src="https://github.com/user-attachments/assets/efa80db3-5da0-4f4b-a31b-3df9861532df" />

**Comment by JoeArmani** [comment]
ready for prod
